/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Notepad;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;

/**
 *
 * @author NSP
 */
public class Fonta extends javax.swing.JFrame {

    /**
     * Creates new form Font
     */
    public Fonta() {
        initComponents();
        setIcon();
        getRootPane().setDefaultButton(jButton1);
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Settings.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        FontPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fontC = new javax.swing.JComboBox<>();
        typeC = new javax.swing.JComboBox<>();
        sizeC = new javax.swing.JComboBox<>();
        preview = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ThemePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Font...");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        FontPanel.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Font...");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Type...");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Size...");

        fontC.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        fontC.setModel(new javax.swing.DefaultComboBoxModel<>(GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames()));
        fontC.setSelectedItem(Notepad.textArea.getFont().getFontName());
        fontC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontCActionPerformed(evt);
            }
        });

        typeC.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        typeC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Bold", "Italic", "Bold Italic" }));
        typeC.setToolTipText("Font Style");
        typeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeCActionPerformed(evt);
            }
        });

        sizeC.setEditable(true);
        sizeC.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        sizeC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72" }));
        sizeC.setSelectedItem(Notepad.textArea.getFont().getSize()
        );
        sizeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeCActionPerformed(evt);
            }
        });

        preview.setEditable(false);
        preview.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        preview.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        preview.setText("AaBbCcDdEeFe12345");
        preview.setToolTipText("");
        preview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        preview.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        preview.setEnabled(false);
        preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Preview...");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FontPanelLayout = new javax.swing.GroupLayout(FontPanel);
        FontPanel.setLayout(FontPanelLayout);
        FontPanelLayout.setHorizontalGroup(
            FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FontPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FontPanelLayout.createSequentialGroup()
                        .addGroup(FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FontPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fontC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(sizeC, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FontPanelLayout.createSequentialGroup()
                        .addGroup(FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preview, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                            .addGroup(FontPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(520, 520, 520)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FontPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addGap(209, 209, 209))))
        );
        FontPanelLayout.setVerticalGroup(
            FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FontPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fontC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(FontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fonts", FontPanel);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Click and see the Magic...");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton3.setText("Regular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton4.setText("Solarized");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton5.setText("Hello Kitty");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton6.setText("Bespin");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton7.setText("Norway Today");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton8.setText("Khaki");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton9.setText("OK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThemePanelLayout = new javax.swing.GroupLayout(ThemePanel);
        ThemePanel.setLayout(ThemePanelLayout);
        ThemePanelLayout.setHorizontalGroup(
            ThemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThemePanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ThemePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ThemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThemePanelLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(ThemePanelLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(119, 119, 119)
                        .addComponent(jButton4)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addGap(117, 117, 117)
                .addGroup(ThemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemePanelLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(20, 20, 20)))
                .addGap(38, 38, 38))
            .addGroup(ThemePanelLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThemePanelLayout.setVerticalGroup(
            ThemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThemePanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(ThemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addGroup(ThemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)))
                .addGap(72, 72, 72)
                .addGroup(ThemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Color Themes", ThemePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fontCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontCActionPerformed
        // TODO add your handling code here:
        int z=0;
        switch (typeC.getSelectedItem().toString()) {
            case "Regular":
                z=Font.PLAIN;
                break;
            case "Bold":
                z=Font.BOLD;
                break;
            case "Italic":
                z=Font.ITALIC;
                break;
            case "Bold Italic":
                z=Font.BOLD+Font.ITALIC;
                break;
            default:
                break;
        }
        preview.setFont(new Font(fontC.getSelectedItem().toString(),z,Integer.parseInt(sizeC.getSelectedItem().toString())));
        
    }//GEN-LAST:event_fontCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int z=0;
        switch (typeC.getSelectedItem().toString()) {
            case "Regular":
                z=Font.PLAIN;
                break;
            case "Bold":
                z=Font.BOLD;
                break;
            case "Italic":
                z=Font.ITALIC;
                break;
            case "Bold Italic":
                z=Font.BOLD+Font.ITALIC;
                break;
            default:
                break;
        }
        Notepad.textArea.setFont(new Font(fontC.getSelectedItem().toString(),z,Integer.parseInt(sizeC.getSelectedItem().toString())));
        super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void typeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeCActionPerformed
        // TODO add your handling code here:
        int z=0;
        switch (typeC.getSelectedItem().toString()) {
            case "Regular":
                z=Font.PLAIN;
                break;
            case "Bold":
                z=Font.BOLD;
                break;
            case "Italic":
                z=Font.ITALIC;
                break;
            case "Bold Italic":
                z=Font.BOLD+Font.ITALIC;
                break;
            default:
                break;
        }
        preview.setFont(new Font(fontC.getSelectedItem().toString(),z,Integer.parseInt(sizeC.getSelectedItem().toString())));
    }//GEN-LAST:event_typeCActionPerformed

    private void sizeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeCActionPerformed
        // TODO add your handling code here:
        int z=0;
        switch (typeC.getSelectedItem().toString()) {
            case "Regular":
                z=Font.PLAIN;
                break;
            case "Bold":
                z=Font.BOLD;
                break;
            case "Italic":
                z=Font.ITALIC;
                break;
            case "Bold Italic":
                z=Font.BOLD+Font.ITALIC;
                break;
            default:
                break;
        }
        preview.setFont(new Font(fontC.getSelectedItem().toString(),z,Integer.parseInt(sizeC.getSelectedItem().toString())));
    }//GEN-LAST:event_sizeCActionPerformed

    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
        // TODO add your handling code here:
        preview.setText("Jai Shree Hanumaan");
    }//GEN-LAST:event_previewActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Notepad.textArea.setBackground(Color.WHITE);
        Notepad.textArea.setForeground(Color.BLACK);
        Notepad.textArea.setSelectionColor(Color.CYAN);
        Notepad.textArea.setCaretColor(Color.BLACK);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Notepad.textArea.setBackground(Color.DARK_GRAY);
        Notepad.textArea.setForeground(Color.LIGHT_GRAY);
        Notepad.textArea.setSelectionColor(Color.BLUE);
        Notepad.textArea.setCaretColor(Color.red);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Notepad.textArea.setBackground(Color.PINK);
        Notepad.textArea.setForeground(Color.BLACK);
        Notepad.textArea.setSelectionColor(Color.LIGHT_GRAY);
        Notepad.textArea.setCaretColor(Color.BLACK);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Notepad.textArea.setBackground(Color.YELLOW);
        Notepad.textArea.setForeground(Color.BLACK);
        Notepad.textArea.setSelectionColor(Color.LIGHT_GRAY);
        Notepad.textArea.setCaretColor(Color.red);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Notepad.textArea.setBackground(Color.BLUE);
        Notepad.textArea.setForeground(Color.WHITE);
        Notepad.textArea.setSelectionColor(Color.BLACK);
        Notepad.textArea.setCaretColor(Color.red);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Notepad.textArea.setBackground(Color.GRAY);
        Notepad.textArea.setForeground(Color.GREEN);
        Notepad.textArea.setSelectionColor(Color.BLACK);
        Notepad.textArea.setCaretColor(Color.red);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fonta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fonta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fonta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fonta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Fonta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FontPanel;
    private javax.swing.JPanel ThemePanel;
    private javax.swing.JComboBox<String> fontC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField preview;
    private javax.swing.JComboBox<String> sizeC;
    private javax.swing.JComboBox<String> typeC;
    // End of variables declaration//GEN-END:variables
}
